### ISSUE TITLE
Adding support for 64-bit data width

### ISSUE THREAD

**Issue by kessam** [enjoy-digital/litedram#147]
Trying to generate a 64-bit data width (DQ) DDR3 core by changing sdram_module_nb parameter to 8, but getting the following error:
I am using MT41J256M16 device

```
ERROR:SoCBusHandler:Region overlap between main_ram and csr:
ERROR:SoCBusHandler:Origin: 0x40000000, Size: 0x80000000, Mode: RW, Cached: True Linker: False
ERROR:SoCBusHandler:Origin: 0x82000000, Size: 0x00010000, Mode: RW, Cached: False Linker: False
Traceback (most recent call last):
  File "gen.py", line 596, in <module>
    main()
  File "gen.py", line 573, in main
    soc      = LiteDRAMCore(platform, core_config, integrated_rom_size=0x6000, integrated_sram_size=0x1000)
  File "gen.py", line 380, in __init__
    controller_settings=controller_settings)
  File "/home/kessam/litex/litex/litex/soc/integration/soc_sdram.py", line 47, in register_sdram
    **kwargs,
  File "/home/kessam/litex/litex/litex/soc/integration/soc.py", line 946, in add_sdram
    self.bus.add_region("main_ram", SoCRegion(origin=origin, size=sdram_size))
  File "/home/kessam/litex/litex/litex/soc/integration/soc.py", line 204, in add_region
    raise
RuntimeError: No active exception to reraise

```

**Comment by enjoy-digital** [comment]
Thanks for reporting, this is fixed by https://github.com/enjoy-digital/litedram/commit/07d24834817e16aefe482c9468fa95cec7b44fe5.
