### ISSUE TITLE
BL8 1:2 controller fails to compile

### ISSUE THREAD

**Issue by JohnSully** [enjoy-digital/litedram#34]
Traceback (most recent call last):
  File "core.py", line 275, in <module>
    main()
  File "core.py", line 256, in main
    soc.generate_sdram_phy_py_header()
  File "core.py", line 240, in generate_sdram_phy_py_header
    self.sdram.controller.settings.timing))
  File "/home/john/repos/litedram/litedram/sdram_init.py", line 292, in get_sdram_phy_py_header
    init_sequence, _ = get_sdram_phy_init_sequence(phy_settings, timing_settings)
  File "/home/john/repos/litedram/litedram/sdram_init.py", line 175, in get_sdram_phy_init_sequence
    mr0 = format_mr0(bl, cl, wr, 1)
  File "/home/john/repos/litedram/litedram/sdram_init.py", line 125, in format_mr0
    mr0 |= wr_to_mr0[wr] << 9
KeyError: 4

The formula computing this uses tWTR*nphases which I think is wrong.  Micron says this should be configured with the following formula:
WR (cycles) = roundup (tWR [ns]/tCK [ns]).

**Comment by enjoy-digital** [comment]
Already fixed with https://github.com/enjoy-digital/litedram/commit/7b61b68f68aea8f67c1f43693be631d0850e058a. tWTR is already rounded up internally and WR is always >= roundup (tWR [ns]/tCK [ns]).
